title: PixelTime
author: PixelTime
email: PixelTime@vip.qq.com
url: https://pixeltimenet.github.io
baseurl: "/Introduction" 
github_username: PixelTimeNet

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
